name: Calidad de código - SonarQube Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Build, tests y análisis SonarQube Cloud

    runs-on: ubuntu-latest

    steps:
      - name: Descargar código de repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Guardar caché del escáner de SonarQube Cloud
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Compilar, correr pruebas y analizar con SonarQube Cloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B verify
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=manuel-romo_orderflow-equipo-rojo
          -Dsonar.organization=manuel-romo
          -Dsonar.qualitygate.wait=true
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml